# SPDX-FileCopyrightText: 2023 Linnea Gr√§f <nea@nea.moe>
#
# SPDX-License-Identifier: CC0-1.0

[versions]
minecraft = "1.21.7"

# Update from https://maven.fabricmc.net/net/fabricmc/fabric-language-kotlin/
fabric_kotlin = "1.13.7+kotlin.2.2.21"
# Update from https://kotlinlang.org/
kotlin = "2.2.21"
# Update from https://github.com/google/ksp/releases
kotlin_ksp = "2.2.21-2.0.4"

# Update from https://linkie.shedaniel.dev/dependencies?loader=fabric
yarn = "1.21.7+build.8"
fabric_loader = "0.16.14"
fabric_api = "0.129.0+1.21.7"
architectury = "17.0.6"
modmenu = "15.0.0-beta.3"
# Update from https://maven.architectury.dev/me/shedaniel/RoughlyEnoughItems-fabric/ (but is typically late)
rei = "19.0.805"
reidev = "33d8900cd6621816680634fcbae2dd07f1cffbd3"

# Update from https://maven.architectury.dev/dev/architectury/loom/dev.architectury.loom.gradle.plugin/
loom = "1.13.457" # TODO: port back to architectury (and) 1.9.424

# Update from https://modrinth.com/mod/qolify/versions?l=fabric
qolify = "1.6.0-1.21.1"

# Update from https://modrinth.com/mod/sodium/versions?l=fabric
sodium = "mc1.21.8-0.7.2-fabric"

# Update from https://modrinth.com/mod/freecam/versions?l=fabric
freecammod = "1.3.4+mc1.21.6"

# Update from https://modrinth.com/mod/no-chat-reports/versions?l=fabric
ncr = "Fabric-1.21.7-v2.14.0"

# Update from https://modrinth.com/mod/female-gender/versions?l=fabric
femalegender = "4.3.4+1.21.7"

# Update from https://modrinth.com/mod/iris/versions?l=fabric
iris = "1.9.6+1.21.8-fabric"

shadow = "8.3.8"


# Update from https://modrinth.com/mod/not-enough-animations/versions?l=fabric
notenoughanimations = "JTLkasT1"

# Update from https://modrinth.com/mod/jade/versions?l=fabric
jade = "19.0.4+fabric"

devauth = "1.2.1"

# Update from https://repo.nea.moe/#/releases/moe/nea/neurepoparser
neurepoparser = "1.8.0"

# Update from https://github.com/HotswapProjects/HotswapAgent/releases
# TODO: bump to 2.0.1
hotswap_agent = "1.4.2-SNAPSHOT"

# Update from https://github.com/LlamaLad7/MixinExtras/tags
mixinextras = "0.5.0"

# Update from https://repo.nea.moe/#/releases/moe/nea/jarvis/
jarvis = "2.0.0"

nealisp = "1.1.0"

# Update from https://github.com/NotEnoughUpdates/MoulConfig/tags
moulconfig = "4.2.0-beta"

# Update from https://repo.nea.moe/#/releases/moe/nea/mc-auto-translations/moe.nea.mc-auto-translations.gradle.plugin
mcAutoTranslations = "0.4.0"

# Update from https://modrinth.com/mod/hypixel-mod-api/versions?l=fabric
hypixelmodapi = "1.0.1"
hypixelmodapi_fabric = "1.0.1+build.1+mc1.21"

# Update from https://github.com/shedaniel/fabric-asm or https://maven.shedaniel.me/me/shedaniel/mm/
manninghamMills = "2.4.1"

# Update from https://docs.isxander.dev/yet-another-config-lib/installing-yacl
# Nvm, they just don't update docs: https://modrinth.com/mod/yacl/versions?l=fabric
yacl = "3.7.1+1.21.6-fabric"

# Update from https://maven.shedaniel.me/me/shedaniel/cloth/basic-math/
basicMath = "0.6.1"

# Update from https://mvnrepository.com/artifact/net.lenni0451.classtransform/core
classtransform = "1.14.1"

# Update from https://mvnrepository.com/artifact/org.ow2.asm/asm/
asm = "9.8"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
fabric_api_deprecated = { module = "net.fabricmc.fabric-api:fabric-api-deprecated", version.ref = "fabric_api" }
fabric_kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric_kotlin" }
architectury = { module = "dev.architectury:architectury", version.ref = "architectury" }

rei_api = { module = "me.shedaniel:RoughlyEnoughItems-api", version.ref = "rei" }
rei_fabric = { module = "me.shedaniel:RoughlyEnoughItems-fabric", version.ref = "rei" }

rei_dev_api = { module = "com.github.shedaniel.roughlyenoughitems:RoughlyEnoughItems-api", version.ref = "reidev" }
rei_dev_fabric = { module = "com.github.shedaniel.roughlyenoughitems:RoughlyEnoughItems-fabric", version.ref = "reidev" }

moulconfig = { module = "org.notenoughupdates.moulconfig:modern-1.21.7", version.ref = "moulconfig" }
repoparser = { module = "moe.nea:neurepoparser", version.ref = "neurepoparser" }
mixinextras = { module = "io.github.llamalad7:mixinextras-fabric", version.ref = "mixinextras" }
jarvis_api = { module = "moe.nea.jarvis:jarvis-api", version.ref = "jarvis" }
jarvis_fabric = { module = "moe.nea.jarvis:jarvis-fabric", version.ref = "jarvis" }
nealisp = { module = "moe.nea:nealisp", version.ref = "nealisp" }
manninghamMills = { module = "me.shedaniel:mm", version.ref = "manninghamMills" }
aaronhmapi = { module = "net.azureaaron:hm-api", version = "1.0.0+1.21" }
hypixelmodapi = { module = "net.hypixel:mod-api", version.ref = "hypixelmodapi" }
hypixelmodapi_fabric = { module = "maven.modrinth:hypixel-mod-api", version.ref = "hypixelmodapi_fabric" }
# Runtime:
notenoughanimations = { module = "maven.modrinth:not-enough-animations", version.ref = "notenoughanimations" }
hotswap = { module = "virtual.github.hotswapagent:hotswap-agent", version.ref = "hotswap_agent" }
architectury_fabric = { module = "dev.architectury:architectury-fabric", version.ref = "architectury" }
devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
modmenu = { module = "maven.modrinth:modmenu", version.ref = "modmenu" }
qolify = { module = "maven.modrinth:qolify", version.ref = "qolify" }
ncr = { module = "maven.modrinth:no-chat-reports", version.ref = "ncr" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }
freecammod = { module = "maven.modrinth:freecam", version.ref = "freecammod" }
femalegender = { module = "maven.modrinth:female-gender", version.ref = "femalegender" }
iris = { module = "maven.modrinth:iris", version.ref = "iris" }
jade = { module = "maven.modrinth:jade", version.ref = "jade" }
yacl = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl" }
basicMath = { module = "me.shedaniel.cloth:basic-math", version.ref = "basicMath" }
shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }
classTransform-mixinsTranslator = { module = "net.lenni0451.classtransform:mixinstranslator", version.ref = "classtransform" }
classTransform-core = { module = "net.lenni0451.classtransform:core", version.ref = "classtransform" }

asm = { module = "org.ow2.asm:asm", version.ref = "asm" }

[bundles]
runtime_required = [
	#	"rei_fabric",
	#	"notenoughanimations",
	"hypixelmodapi_fabric",
]
runtime_optional = [
	"devauth",
	#	"freecammod",
	#	"sodium",
	#	"qolify",
	#	"ncr",
]

[plugins]
kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin_plugin_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin_plugin_powerassert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
kotlin_plugin_ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin_ksp" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
loom = { id = "dev.architectury.loom", version.ref = "loom" }
mcAutoTranslations = { id = "moe.nea.mc-auto-translations", version.ref = "mcAutoTranslations" }
